spring:
  profiles:
    active: local, dev
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
#  sql:
#    init:
#      data-locations: classpath:db/district.sql,
#        classpath:db/location.sql,
#        classpath:db/category.sql,
#        classpath:db/category_location.sql,
#        classpath:db/users.sql,
#        classpath:db/reels.sql,
#        classpath:db/news.sql
#
#      mode: always
#  main:
#    allow-circular-references: true
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2KB
#      max-file-size: 200MB
#      max-request-size: 215MB
aws-cloud:
  access-key: ${ACCESS_KEY:}
  secret-key: ${SECRET_KEY:}
  bucket-image: ${BUCKET_IMAGE:}
  origin-path: ${ORIGIN_PATH:}