#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/food
#    username: gmit
#    password: abc123
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
